# Generated by Django 5.2.5 on 2025-08-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuario.modalidade')),
            ],
        ),
    ]
