# Generated by Django 5.2.5 on 2025-08-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='descricao',
        ),
    ]
